# Generated by Django 5.0.14 on 2026-09-20 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un plato con ese nombre en la carta.'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres.')], verbose_name='Nombre del plato')),
                ('descripcion', models.TextField(help_text='Ingredientes principales o forma de preparación (máx. 300 caracteres).', max_length=300, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('ENT', 'Entrada'), ('FON', 'Plato de fondo'), ('POS', 'Postre'), ('BEB', 'Bebida')], default='FON', max_length=3, verbose_name='Categoría')),
                ('precio', models.PositiveIntegerField(help_text='Precio en pesos chilenos, sin puntos ni decimales.', validators=[django.core.validators.MinValueValidator(1, 'El precio debe ser mayor que cero.'), django.core.validators.MaxValueValidator(500000, 'El precio no puede superar los $500.000.')], verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad de porciones disponibles hoy. No puede ser negativo.', verbose_name='Porciones disponibles')),
                ('tiempo_preparacion', models.PositiveSmallIntegerField(help_text='Minutos que demora la preparación.', validators=[django.core.validators.MinValueValidator(1, 'El tiempo de preparación debe ser de al menos 1 minuto.'), django.core.validators.MaxValueValidator(180, 'El tiempo de preparación no puede superar los 180 minutos.')], verbose_name='Tiempo de preparación')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible en carta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'carta_plato',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
